[2024-11-15T15:24:37.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dag.load_and_preprocess_data manual__2024-11-15T15:24:35.047754+00:00 [queued]>
[2024-11-15T15:24:37.634+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dag.load_and_preprocess_data manual__2024-11-15T15:24:35.047754+00:00 [queued]>
[2024-11-15T15:24:37.634+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-11-15T15:24:37.642+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_and_preprocess_data> on 2024-11-15 15:24:35.047754+00:00
[2024-11-15T15:24:37.648+0000] {standard_task_runner.py:60} INFO - Started process 2040 to run task
[2024-11-15T15:24:37.650+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dag', 'load_and_preprocess_data', 'manual__2024-11-15T15:24:35.047754+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/random.py', '--cfg-path', '/tmp/tmpd0mjsbut']
[2024-11-15T15:24:37.651+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask load_and_preprocess_data
[2024-11-15T15:24:37.679+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_dag.load_and_preprocess_data manual__2024-11-15T15:24:35.047754+00:00 [running]> on host 8b834e0277f8
[2024-11-15T15:24:37.719+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='suvarna' AIRFLOW_CTX_DAG_ID='ml_pipeline_dag' AIRFLOW_CTX_TASK_ID='load_and_preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T15:24:35.047754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T15:24:35.047754+00:00'
[2024-11-15T15:24:37.736+0000] {random.py:45} ERROR - Error in loading or preprocessing data: type object 'BaseXCom' has no attribute 'push'
[2024-11-15T15:24:37.736+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/random.py", line 46, in load_and_preprocess_data
    raise e
  File "/opt/airflow/dags/random.py", line 42, in load_and_preprocess_data
    return XCom.push(key="data", value=(X_train, X_test, y_train, y_test))
AttributeError: type object 'BaseXCom' has no attribute 'push'
[2024-11-15T15:24:37.742+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_dag, task_id=load_and_preprocess_data, execution_date=20241115T152435, start_date=20241115T152437, end_date=20241115T152437
[2024-11-15T15:24:37.749+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task load_and_preprocess_data (type object 'BaseXCom' has no attribute 'push'; 2040)
[2024-11-15T15:24:37.790+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-15T15:24:37.801+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
